m = input('Please input number  1\n')
n = input('Please input number  2\n')
o = input('Please input number  3\n')
p = input('Please input number  4\n')
q = input('Please input number  5\n')
print('float of 1 equal ',float(m))
print('complex of 1 equal ',complex(m))
print('float of 2 equal ',float(n))
print('complex of 2 equal ',complex(n))
print('float of 3 equal ',float(o))
print('complex of 3 equal ',complex(o))
print('float of 4 equal ',float(p))
print('complex of 4 equal ',complex(p))
print('float of 5 equal ',float(q))
print('complex of 5 equal ',complex(q))